### ISSUE TITLE
Add rel option

### ISSUE THREAD

**Issue by crookedneighbor** [crookedneighbor/markdown-it-link-target#1]
See https://jakearchibald.com/2016/performance-benefits-of-rel-noopener/ for why this is important.

**Comment by dashed** [comment]
@crookedneighbor I'm wondering if this npm module can be renamed to `markdown-it-link-attributes` that will just **generally** inject attributes (not just `target`) from a given object:

``` js
md.use(milt, {
  target: '_top',
  ref: 'nofollow me noopener noreferrer',
  foo: 'bar'
});
var html = md.render('![link](https://google.com)')
html // <p><a href="https://google.com" target="_top" rel="nofollow me noopener noreferrer" foo="bar">link</a></p>
```

**Comment by crookedneighbor** [comment]
That's a great idea! Done: https://www.npmjs.com/package/markdown-it-link-attributes

**Comment by dashed** [comment]
@crookedneighbor that was fast! 😄  

I was using `markdown-it-for-inline`, but now I'll be using your `markdown-it-link-attributes` module which works fine for me. Thanks! 👍
